[phases.setup]
nixpkgs = ['python311', 'pip']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '. /opt/venv/bin/activate && pip install --upgrade pip',
  '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = '. /opt/venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 30 app:app'